# Generated by Django 4.2.5 on 2024-04-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.CharField(choices=[('seller1', 'Seller 1 - Address 1'), ('seller2', 'Seller 2 - Address 2'), ('seller3', 'Seller 3 - Address 3')], default='seller1', max_length=10),
        ),
    ]
