# Generated by Django 4.2.5 on 2024-04-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='seller',
            field=models.CharField(choices=[('seller1', 'seller-1<br>John Doe<br>456, Gandhi Road,<br>Anna Nagar,<br>Chennai - 600001,<br>Tamil Nadu, India.'), ('seller2', 'seller-2<br>Jane Doe<br>789, Marina Road,<br>Madipakkam,<br>Chennai - 600002,<br>Tamil Nadu, India.'), ('seller3', 'seller-3<br>John Smith<br>123, Mount Road,<br>Tambaram,<br>Chennai - 600003,<br>Tamil Nadu, India.')], default='seller1', max_length=10),
        ),
    ]
